services:
  - type: web
    name: my-express-app
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: SESSION_SECRET
        sync: false # Defina como true se você quiser sincronizar com um Secret Group
        value: sua_chave_secreta_aqui # Substitua pela chave secreta real ou configure um Secret Group
    staticPublishPath: public

    # Configuração do serviço do SQLite
    sqlite:
      - name: database
        databaseFile: database.sqlite
        migrationsDir: migrations # Certifique-se de que este diretório exista e contenha suas migrações

    # Opções de saúde e tempo limite
    healthCheckPath: '/'
    autoDeploy: true
    buildTimeoutSeconds: 600 # Ajuste conforme necessário

    # Volume para persistência de dados
    volumes:
      - name: sqlite-data
        mountPath: /data

    # Caminhos de log
    logs:
      - type: stdout
        path: /var/log/my-express-app.log

    # Eventos de ciclo de vida do serviço
    lifecycle:
      postdeploy:
        - command: 'npm run migrate' # Certifique-se de que esse comando exista no seu package.json
          name: 'Run migrations'
