services:
  - type: web
    name: cadastro-pet
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: SESSION_SECRET
        sync: false
        value: sua_chave_secreta_aqui
      # Variáveis de ambiente para se conectar ao PostgreSQL
      - key: PGUSER
        value: cadastrope_db_user
      - key: PGHOST
        value: dpg-cpb24lo21fec739au4ng-a
      - key: PGDATABASE
        value: cadastrope_db
      - key: PGPASSWORD
        value: gdZ4SNLQMwYASonDB8fyyl4PHRRZRlhs
      - key: PGPORT
        value: '5432' // Porta padrão do PostgreSQL

    staticPublishPath: public

    # Opções de saúde e tempo limite
    healthCheckPath: '/'
    autoDeploy: true
    buildTimeoutSeconds: 600

    # Volume para persistência de dados
    volumes:
      - name: postgresql-data // Renomeie o volume para postgresql-data
        mountPath: /data

    # Eventos de ciclo de vida do serviço
    lifecycle:
      postdeploy:
        - command: 'npm run migrate'
          name: 'Run migrations'
